# Generated by Django 5.2.17 on 2026-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedConfirmation',
            fields=[
                ('token_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
